version: "3.9"

services:
    api:
        restart: unless-stopped
        build:
            context: .
            dockerfile: ./docker/production/express/Dockerfile
        environment:
            - NODE_ENV=production
        env_file:
            - ./.env
        ports:
            - "1997"
      